# # Use Node.js for both building and running
# FROM node:22

# # Set working directory
# WORKDIR /app

# # Copy package files first (for caching)
# COPY CYDocs-front/package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the project
# COPY CYDocs-front/. .

# # Ensure local binaries are executable (fix for some Linux permissions)
# RUN chmod +x ./node_modules/.bin/vite
# RUN chmod +x node_modules/@esbuild/linux-x64/bin/esbuild

# # Build the app using the local vite binary
# RUN npm run build

# # Expose port
# EXPOSE 5173

# # Install a static server globally to serve the build
# RUN npm install -g serve

# # Start the server
# CMD ["serve", "-s", "dist", "-l", "5173"]


FROM node:22

WORKDIR /app

# 1. Copier uniquement les fichiers de configuration
COPY CYDocs-front/package*.json ./

# 2. Installer les dépendances PROPREMENT dans le conteneur
RUN npm install

# 3. Copier le reste du code (SANS le node_modules du Mac)
COPY CYDocs-front/. .

# 4. Supprimer les lignes chmod qui font planter le build
 RUN chmod +x ./node_modules/.bin/vite  
 RUN chmod +x node_modules/@esbuild/linux-x64/bin/esbuild 

# 5. Build et Serve
RUN npm run build
EXPOSE 5173
RUN npm install -g serve
CMD ["serve", "-s", "dist", "-l", "5173"]