version: "3.9"

services:
  user_management_service:
    image: user_management
    container_name: user_management
    ports:
      - "8081:8080"

  document_management_service:
    image: document_management
    container_name: document_management
    ports:
      - "8082:8080"
