# Use a lightweight JDK base image
FROM eclipse-temurin:25-jdk-alpine

# Set working directory inside the container
WORKDIR /app

# Copy the built JAR into the container
COPY /service/target/demo-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
