FROM nginx:latest

# Install Consul Template
RUN apt-get update && apt-get install -y wget unzip && \
    wget https://releases.hashicorp.com/consul-template/0.36.0/consul-template_0.36.0_linux_amd64.zip && \
    unzip consul-template_0.36.0_linux_amd64.zip && \
    mv consul-template /usr/local/bin/ && \
    rm -rf /var/lib/apt/lists/*

# Copy template and config
COPY nginx.conf.tpl /etc/consul-template/nginx.conf.tpl
COPY consul-template.hcl /etc/consul-template/consul-template.hcl

# Start consul-template (which will run nginx as needed)
CMD consul-template -config=/etc/consul-template/consul-template.hcl
