# Image Nginx native pour Mac (Alpine est très légère)
FROM nginx:alpine

# Installation de consul-template version ARM64 (Mac M1/M2/M3)
# On télécharge directement le binaire correspondant à votre processeur
ADD https://releases.hashicorp.com/consul-template/0.36.0/consul-template_0.36.0_linux_arm64.zip /tmp/
RUN unzip /tmp/consul-template_0.36.0_linux_arm64.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/consul-template && \
    rm /tmp/consul-template_0.36.0_linux_arm64.zip

# Dossiers de configuration
RUN mkdir -p /etc/consul-template /etc/nginx/conf.d

# Copie de vos fichiers
COPY consul-template.hcl /etc/consul-template/consul-template.hcl
COPY nginx.conf.tpl /etc/consul-template/nginx.conf.tpl

# Suppression de la config par défaut
RUN rm -f /etc/nginx/conf.d/default.conf

# Lancement
CMD ["consul-template", "-config=/etc/consul-template/consul-template.hcl"]